license_plate_patterns:
    # Australia license plate patterns
    AU:
        PREMIUM:
            WA: "^\\d{1,3}[A-Z]{1,3}$"  # WA Premium Plates
            TAS: "^\\d{1,3}[A-Z]{1,3}$"  # TAS Premium Plates
            NT: "^\\d{1,3}[A-Z]{1,3}$"  # NT Premium Plates
            ACT: "^\\d{1,3}\\s?[A-Z]{1,3}$"  # ACT Premium Plates
            VIC: "^\\d{1,3}[A-Z]{1,3}$"  # VIC Premium Plates
            SA: "^\\d{1,3}[A-Z]{1,3}$"  # SA Premium Plates
            NSW: "^[A-Z]{1,3}\\d{1,3}$"  # NSW Premium Plates
            QLD: "^\\d{1,3}[A-Z]{1,3}$"  # QLD Premium Plates
        STANDARD:
            VIC: "^[A-Z]{3}\\d{3}$"  # Victoria
            QLD: "^\\d{3}[A-Z]{3}$"  # Queensland
            WA: "^\\d{1,2}[A-Z]{1,2}\\d{1,2}$"  # Western Australia
            NT: "^[A-Z]{1}\\d{2}[A-Z]{1}\\d{3}$"  # Northern Territory
            TAS: "^[A-Z]{3}\\d{3}$"  # Tasmania
            NSW:
                - "^[A-Z]{3}\\d{2}[A-Z]$"  # Three letters, two numbers, one letter
                - "^[A-Z]{2}\\d{2}[A-Z]{2}$"  # Two letters, two numbers, two letters
            SA: "^[A-Z]{3}\\d{3}$"  # South Australia
        SPECIAL:
            QLD_FARM_1: "^1[A-Z]·\\d{3}$"  # QLD Farm Plates (1A·NNN format)
            NSW_HISTORIC: "^\\d{5}J$"  # NSW Historic Vehicle
            QLD_TAXI: "^T·\\d{5}$"  # QLD Taxi Plates
            QLD_FARM_2: "^F·\\d{5}$"  # QLD Farm Plates (F·NNNNN format)
            NSW_CLASSIC: "^\\d{4}D$"  # NSW Classic Cycle
            QLD_FARM: "^[A-Z]\\d{5}$"  # QLD Farm Plates
            VIC_PRIMARY: "^\\d{5}P$"  # VIC Primary Producer
            QLD_LIMOUSINE: "^L·\\d{5}$"  # QLD Limousine Plates
            NSW_RALLY: "^\\d{5}R$"  # NSW Rally Permit
            QLD_SPECIAL_LIMOUSINE: "^SL·\\d{2}·[A-Z]{2}$"  # QLD Special Purpose Limousines
            VIC_CLUB: "^\\d{4}H\\d$"  # VIC Club Permit
            QLD_SEQUENTIAL: "^\\d{3}·[A-Z]\\d{1}[A-Z]$"  # QLD Sequential Series
            NSW_CONDITIONAL: "^\\d{5}E$"  # NSW Conditional
            QLD_GOVERNMENT: "^QG·[A-Z]{2}\\d{2}$"  # QLD Government Used Vehicles
            WA_PLATINUM: "^1F[A-Z]{2}\\d{3}$"  # WA Platinum Slimline
        TRAILER:
            VIC: "^\\d{3}\\d{2}C$"  # VIC Trailer
            TAS: "^[A-Z]\\d{2}[A-Z]{2}$"  # TAS Trailer
            ACT: "^T\\d{4}[A-Z]?$"  # ACT Trailer
            NT: "^T[A-Z]\\d{4}$"  # NT Trailer
            QLD: "^\\d{3}U[A-Z]{2}$"  # QLD Trailer
            SA: "^S\\d{3}T[A-Z]{2}$"  # SA Trailer
            NSW: "^T[A-Z]\\d{2}[A-Z]{2}$"  # NSW Trailer
            WA: "^1U[A-Z]{2}\\d{3}$"  # WA Trailer
        MOTORCYCLE:
            VIC: "^3D[A-Z]\\d{2}$"  # VIC Motorcycle
            ACT: "^C\\d{4}$"  # ACT Motorcycle
            TAS: "^C\\d{3}[A-Z]$"  # TAS Motorcycle
            NT: "^C\\d{4}$"  # NT Motorcycle
            SA: "^S\\d{2}[A-Z]{3}$"  # SA Motorcycle
            WA: "^1L[A-Z]{2}\\d{3}$"  # WA Motorcycle
            QLD: "^3[A-Z]{2}\\d{2}$"  # QLD Motorcycle
            NSW: "^[A-Z]{3}\\d{2}$"  # NSW Motorcycle
    # New Zealand license plate patterns
    NZ:
        TRAILER: "^T\\d{4}$"  # Trailer plates
        PERSONALIZED: "^[A-Z0-9]{1,6}$"  # Personalized plates
        MOTORCYCLE: "^[A-Z]{1,3}\\d{1,4}$"  # Motorcycle plates
        STANDARD: "^[A-Z]{1,3}\\d{1,4}$"  # Standard plates
    # United Kingdom license plate patterns
    UK:
        SUFFIX: "^[A-Z]{3}\\s?\\d{1,3}[A-Z]$"  # Suffix format (1963–1983)
        NORTHERN_IRELAND: "^[A-Z]{1,3}\\d{1,4}$"  # Northern Ireland format
        PREFIX: "^[A-Z]\\d{1,3}\\s?[A-Z]{3}$"  # Prefix format (1983–2001)
        CURRENT: "^[A-Z]{2}\\d{2}\\s?[A-Z]{3}$"  # Current format (since 2001)
    # United States license plate patterns (generalized)
    US:
        PERSONALIZED: "^[A-Z0-9]{1,7}$"  # Personalized plates (varies by state)
        STANDARD: "^[A-Z0-9]{1,7}$"  # Standard plates (varies by state)
    # Canada license plate patterns (generalized)
    CA:
        PERSONALIZED: "^[A-Z0-9]{1,7}$"  # Personalized plates (varies by province)
        STANDARD: "^[A-Z0-9]{1,7}$"  # Standard plates (varies by province)
    # Germany license plate patterns
    DE:
        STANDARD: "^[A-Z]{1,3}-[A-Z]{1,2}\\s?\\d{1,4}[H]?$"  # Standard plates with optional historic vehicle 'H'
    # France license plate patterns
    FR:
        STANDARD: "^[A-Z]{2}-\\d{3}-[A-Z]{2}$"
    # Japan license plate patterns
    JP:
        COMMERCIAL: "^[\\p{Script=Han}]{1,2}\\d{2,3}[\\p{Hiragana}]{1}\\d{2}-\\d{2}$"  # Commercial plates follow the same format as standard plates
        DIPLOMATIC: "^\\d{2}-\\d{2}\\s?[A-Z]{1,2}$"  # Diplomatic plates: White background with black characters, format varies
        K_CLASS: "^[\\p{Script=Han}]{1,2}\\d{2,3}[\\p{Hiragana}]{1}\\d{2}-\\d{2}$"  # Kei car plates: Yellow background with black characters
        STANDARD: "^[\\p{Script=Han}]{1,2}\\d{2,3}[\\p{Hiragana}]{1}\\d{2}-\\d{2}$"  # Standard plates: Region code in Kanji, vehicle class number, hiragana character, and serial number
    # India license plate patterns
    IN:
        STANDARD: "^[A-Z]{2}\\s?\\d{1,2}\\s?[A-Z]{1,3}\\s?\\d{4}$"  # Standard plates: State code, district code, optional letters, and serial number
    # China license plate patterns
    CN:
        POLICE: "^GA[A-Z]{2}-\\d{4}$"  # Police vehicles: 'GA' followed by two letters and four digits
        NEW_ENERGY: "^[\\p{Script=Han}]{1}[A-Z]\\s?[A-Z0-9]{6}$"  # New energy vehicles: Similar to standard but with six alphanumeric characters
        STANDARD: "^[\\p{Script=Han}]{1}[A-Z]\\s?[A-Z0-9]{5}$"  # Standard plates: Province code in Han characters, letter, and five alphanumeric characters
    # United Arab Emirates license plate patterns
    UAE:
        AJMAN: "^[A-H]\\d{1,5}$"  # Ajman plates: Single letter and up to five digits
        FUJAIRAH: "^[A-GKMPRST]\\d{1,5}$"  # Fujairah plates: Single letter and up to five digits
        SHARJAH: "^(?:[1-5]\\s?)?\\d{1,5}$"  # Sharjah plates: Optional single digit and up to five digits
        ABU_DHABI: "^(1[0-9]?|[4-9]|1[0-9]|2[0-1]|50)\\s?\\d{1,5}$"  # Abu Dhabi plates: Category number and up to five digits
        DUBAI: "^[A-Z]{1,2}\\d{1,5}$"  # Dubai plates: One or two letters and up to five digits
        RAS_AL_KHAIMAH: "^[ACDIKMNSVY]\\d{1,5}$"  # Ras Al Khaimah plates: Single letter and up to five digits
        UMM_AL_QUWAIN: "^[A-IX]\\d{1,5}$"  # Umm Al Quwain plates: Single letter and up to five digits
    # Hong Kong license plate patterns
    HK:
        PRIVATE: "^[A-Z]{2}\\s?\\d{3,4}$"  # Private vehicles: Two letters followed by three or four digits
    # Iran license plate patterns
    IR:
        STANDARD: "^\\d{2}[\\u0600-\\u06FF]\\d{3}$"  # Standard plates: Two digits, a Persian letter, and three digits
    # Ukraine license plate patterns
    UA:
        TEMPORARY: "^\\d{2}-\\d{2}-\\d{4}-\\d{2}$"  # Temporary plates: Two digits, two digits, four digits, and two digits
        MOTORCYCLE: "^[A-Z]{2}\\d{4}M[A-Z]$"  # Motorcycle plates: Similar to standard with an 'M' before the final letter
        DIPLOMATIC: "^\\d{2}-\\d{2}-\\d{4}$"  # Diplomatic plates: Two digits, two digits, and four digits
        TRAILER: "^[A-Z]{2}\\d{4}X[A-Z]$"  # Trailer plates: Similar to standard with an 'X' before the final letter
        STANDARD: "^[A-Z]{2}\\d{4}[A-Z]{2}$"  # Standard plates: Two letters, four digits, and two letters
